//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneDBModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderID { get; set; }
        public string customerName { get; set; }
        public string fulfilmentStatus { get; set; }
        public string pickupAddress { get; set; }
        public string vehicleType { get; set; }
        public string destinationAddress { get; set; }
        public string createdTime { get; set; }
        public string readyTime { get; set; }
        public string dispatchedTime { get; set; }
        public string weight { get; set; }
        public string numberOfPieces { get; set; }
        public string serviceType { get; set; }
        public string packageType { get; set; }
        public string referenceNumber { get; set; }
        public string bilableAddress { get; set; }
        public string isRoundTrip { get; set; }
        public string assignedDriverID { get; set; }
        public int Client_accountID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
