//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneDBModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int reportID { get; set; }
        public string desiredTimeFrame { get; set; }
        public string generatedDateTime { get; set; }
        public string isContainingGraphs { get; set; }
        public string isContainingCharts { get; set; }
        public string title { get; set; }
        public string customReportingConstraints { get; set; }
        public string generatedBy { get; set; }
        public string accountNumber { get; set; }
        public string customerName { get; set; }
        public string numberOfOrders { get; set; }
        public string expenses { get; set; }
        public string previousOrdersPlaced { get; set; }
        public string numberOfClientOrdersPlaced { get; set; }
        public string clientNames { get; set; }
        public int Client_accountID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
