//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneDBModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int reportID { get; set; }
        public byte[] desiredTimeFrame { get; set; }
        public System.TimeSpan generatedDateTime { get; set; }
        public bool isContainingGraphs { get; set; }
        public bool isContainingCharts { get; set; }
        public string title { get; set; }
        public string customReportingConstraints { get; set; }
        public string generatedBy { get; set; }
        public string accountNumber { get; set; }
        public string customerName { get; set; }
        public Nullable<int> numberOfOrders { get; set; }
        public Nullable<double> expenses { get; set; }
        public Nullable<int> previousOrdersPlaced { get; set; }
        public Nullable<int> numberOfClientOrdersPlaced { get; set; }
        public string clientNames { get; set; }
        public int Client_accountID { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
