//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneDBModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int shipmentID { get; set; }
        public string driverNotes { get; set; }
        public string paperWaybillNumber { get; set; }
        public string pickedUpTime { get; set; }
        public string confirmedTime { get; set; }
        public string deliveryTime { get; set; }
        public int Driver_driverID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
